name: SKT_FLY_AI
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4  # 최신 버전 사용 가능
  intl: ^0.17.0


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  image_picker: ^0.8.7+5
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
   - family: moebiusBold
     fonts:
       - asset: assets\fonts\moebius_Bold.ttf
   - family: moebiusRegular
     fonts:
       - asset: assets\fonts\moebius_Regular.ttf

  assets:
    - assets/
    - assets/icons/
    - assets/icons/home/
    - assets/splash/
    - assets/icons/navigation/
    - assets/icons/menu/
    - assets/icons/input/
    - assets/icons/choice/
    - assets/icons/diary/
    - assets/icons/loading/
    - assets/images/home/

  



    
